import{a as y,S as h,i as c}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const b="49602919-aeba24ff5374aa13ccf20c3b1",P="https://pixabay.com/api/",i={image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function L(a,r=1){try{const t=await y.get(`${P}`,{params:{key:b,q:a,image_type:i.image_type,orientation:i.orientation,safesearch:i.safesearch,page:r,per_page:i.per_page}});return console.log("response_func",t),{data:t.data,totalPages:_(t),page:t.config.params.page}}catch(t){console.error("Error fetching data from Pixabay:",t)}finally{}}function _(a){return Math.ceil(a.data.totalHits/a.config.params.per_page)}const d=document.querySelector(".gallery"),p=document.querySelector(".loader"),A=document.querySelector(".load-more");async function v(a){try{const r=await a;console.log("createGallery",r);const t=r.map(({webformatURL:n,largeImageURL:e,tags:o,likes:s,views:m,comments:f,downloads:g})=>`<li class="gallery-item">
                  <a href="${e}">
                    <img class="gallery-image" src="${n}" alt="${o}" />
                    <div class='item-footer'>
                      <p><b>likes</b> ${s}</p>
                      <p><b>views</b> ${m}</p>
                      <p><b>comments</b> ${f}</p>
                      <p><b>downloads</b> ${g}</p>
                    </div>
                  </a>
                </li>`).join("");d.innerHTML=t,x.refresh()}catch(r){console.error("Error creating gallery:",r)}}function S(){d.innerHTML=""}function w(){p.classList.remove("hidden-loader")}function $(){p.classList.add("hidden-loader")}function q(){A.classList.remove("load-more-hidden")}const x=new h(".gallery a",{}),l=document.querySelector(".form");document.querySelector(".load-more");let u="",I=10;l.addEventListener("submit",async a=>{if(a.preventDefault(),u=l.elements["search-text"].value,S(),u===""){c.error({message:"Please enter a search inputValue!",position:"topRight",timeout:2e3});return}w();const r=L(u,I);console.log("DATA",r),r.then(t=>{if(console.log("response!!!",t),t.data.hits.length===0){c.error({message:"Sorry, there are no images matching your search inputValue. Please try again!",position:"topRight",timeout:2e3});return}console.log("response_main",t),v(t.data.hits),q()}).catch(()=>{c.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}).finally(()=>{$()}),l.reset()});
//# sourceMappingURL=index.js.map
