import{a as A,S as v,i as s}from"./assets/vendor-B2xQfKYm.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const S="49602919-aeba24ff5374aa13ccf20c3b1",w="https://pixabay.com/api/",c={image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function p(a,o){try{const e=await A.get(`${w}`,{params:{key:S,q:a,image_type:c.image_type,orientation:c.orientation,safesearch:c.safesearch,page:o,per_page:c.per_page}});return console.log("response_func",e),{data:e.data,hits:e.data.hits,totalPages:M(e),page:e.config.params.page}}catch(e){console.error("Error fetching data from Pixabay:",e)}finally{}}function M(a){return Math.ceil(a.data.totalHits/a.config.params.per_page)}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more");async function y(a){try{const o=await a;console.log("createGallery",o),console.log("items",o.hits);const e=o.hits.map(({webformatURL:i,largeImageURL:t,tags:r,likes:n,views:L,comments:P,downloads:_})=>`<li class="gallery-item">
                  <a href="${t}">
                    <img class="gallery-image" src="${i}" alt="${r}" />
                    <div class='item-footer'>
                      <p><b>likes</b> ${n}</p>
                      <p><b>views</b> ${L}</p>
                      <p><b>comments</b> ${P}</p>
                      <p><b>downloads</b> ${_}</p>
                    </div>
                  </a>
                </li>`).join("");m.insertAdjacentHTML("beforeend",e),o.page===o.totalPages&&(x(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3})),B.refresh()}catch(o){console.error("Error creating gallery:",o)}}function q(){m.innerHTML=""}function h(){f.classList.remove("hidden-loader")}function b(){f.classList.add("hidden-loader")}function E(){g.classList.remove("load-more-hidden")}function x(){g.classList.add("load-more-hidden")}const B=new v(".gallery a",{}),u=document.querySelector(".form"),$=document.querySelector(".load-more");let l=null,d=null;u.addEventListener("submit",async a=>{if(a.preventDefault(),d=1,l=u.elements["search-text"].value,q(),l===""){s.error({message:"Please enter a search inputValue!",position:"topRight",timeout:2e3});return}h(),p(l,d).then(e=>{if(console.log("response!!!",e),e.data.hits.length===0){s.error({message:"Sorry, there are no images matching your search inputValue. Please try again!",position:"topRight",timeout:2e3});return}console.log("response_main",e),y(e),E()}).catch(()=>{s.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}).finally(()=>{b()}),u.reset()});$.addEventListener("click",I);async function I(){d+=1,console.log("click");const a=document.querySelector(".loader-wraper");document.querySelector(".gallery").insertAdjacentElement("afterend",a),h();try{const e=await p(l,d);y(e)}catch{s.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}finally{b()}}
//# sourceMappingURL=index.js.map
