import{a as v,S as A,i as d}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const M="49602919-aeba24ff5374aa13ccf20c3b1",S="https://pixabay.com/api/",i={image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function p(a,o){try{const t=await v.get(`${S}`,{params:{key:M,q:a,image_type:i.image_type,orientation:i.orientation,safesearch:i.safesearch,page:o,per_page:i.per_page}});return console.log("response_func",t),{data:t.data,hits:t.data.hits,totalPages:w(t),page:t.config.params.page}}catch(t){console.error("Error fetching data from Pixabay:",t)}finally{}}function w(a){return Math.ceil(a.data.totalHits/a.config.params.per_page)}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".load-more");async function h(a){try{const o=await a;console.log("createGallery",o),console.log("items",o.hits);const t=o.hits.map(({webformatURL:s,largeImageURL:e,tags:r,likes:n,views:b,comments:P,downloads:_})=>`<li class="gallery-item">
                  <a href="${e}">
                    <img class="gallery-image" src="${s}" alt="${r}" />
                    <div class='item-footer'>
                      <p><b>likes</b> ${n}</p>
                      <p><b>views</b> ${b}</p>
                      <p><b>comments</b> ${P}</p>
                      <p><b>downloads</b> ${_}</p>
                    </div>
                  </a>
                </li>`).join("");f.innerHTML=t,o.page===o.totalPages&&q(),x.refresh()}catch(o){console.error("Error creating gallery:",o)}}function B(){f.innerHTML=""}function y(){m.classList.remove("hidden-loader")}function L(){m.classList.add("hidden-loader")}function $(){g.classList.remove("load-more-hidden")}function q(){g.classList.add("load-more-hidden")}const x=new A(".gallery a",{}),u=document.querySelector(".form"),E=document.querySelector(".load-more");let c=null,l=null;u.addEventListener("submit",async a=>{if(a.preventDefault(),l=1,c=u.elements["search-text"].value,B(),c===""){d.error({message:"Please enter a search inputValue!",position:"topRight",timeout:2e3});return}y(),p(c,l).then(t=>{if(console.log("response!!!",t),t.data.hits.length===0){d.error({message:"Sorry, there are no images matching your search inputValue. Please try again!",position:"topRight",timeout:2e3});return}console.log("response_main",t),h(t),$()}).catch(()=>{d.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}).finally(()=>{L()}),u.reset()});E.addEventListener("click",I);async function I(){l+=1,console.log("click"),y();const a=await p(c,l);h(a),L()}
//# sourceMappingURL=index.js.map
